---
# must execute erlang role before elixir role
- name: check elixir presence
  command: which elixir
  ignore_errors: true
  register: elixir_path

- name: download elixir
  sudo: yes
  get_url: url=https://github.com/elixir-lang/elixir/releases/download/v1.5.1/Precompiled.zip dest={{ src_dir }}
  when: elixir_path.rc != 0

- name: change owner of install dir
  sudo: yes
  command: chgrp -R {{ app_user }} {{ src_dir }}
  when: elixir_path.rc != 0

- name: change mode of install dir
  sudo: yes
  command: chmod -R g+rwxXs {{ src_dir }}
  when: elixir_path.rc != 0

- name: unzip elixir_src
  shell: bash -lc "sudo unzip Precompiled.zip -d /opt/elixir"
  args:
    chdir: "{{ src_dir }}"
    creates: "/opt/elixir"
  when: elixir_path.rc != 0

- name: add elixir to path
  sudo: yes
  copy: src=elixir_path.sh dest=/etc/profile.d mode=0775
  when: elixir_path.rc != 0

- name: install hex
  shell: bash -lc "/opt/elixir/bin/mix local.hex"
  when: elixir_path.rc != 0
